# CI pipeline for the Vi-Ui live demo
#
# We're currently assessing the possibility of hosting this live demo
# in our own cloud infrastructure.
# An alternative is using Netlify's hosting service, but I believe an
# S3 static-site bucket will do just as well.

language: node_js
node_js:
  - '10'

jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run coverage:collect

    - stage: build
      script:
        - echo "This is the build phase"
        - npm run build
        - npm run styleguide:build
      deploy:
        provider: pages
        skip_cleanup: true
        fqdn: viui.dev
        commiter_from_gh: true
        github_token: $GITHUB_TOKEN
        on:
          branch: master
        target_branch: gh-pages
        local_dir: docs
